# Executar com: docker-compose up -d
# Cria banco de dados MySQL ada_db com usuário root e senha root na porta 3306
# Cria server keycloak, user admin e senha admin, porta 8088
# Cria client Redis para cache, porta 6379
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth/realms/quarkus
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8088:8080"
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

volumes:
  mysql_data: